export const GET_PARKINGS = "GET_PARKINGS";
export const ADD_PARKING = "ADD_PARKING";
export const UPDATE_PARKING = "UPDATE_PARKING";
export const GETSINGLE_PARKING = "GETSINGLE_PARKING";
export const DELETE_PARKING = "DELETE_PARKING";
export const SEARCH_PARKING = "SEARCH_PARKING";
